// Date: 26-5-2013 0:50:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package pneumaticCraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFlowDetector extends ModelBase{
    // fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;

    public ModelFlowDetector(){
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 3, 4, 1);
        Shape1.setRotationPoint(-1.5F, 14F, 3F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);

        Shape2 = new ModelRenderer(this, 0, 5);
        Shape2.addBox(0F, 0F, 0F, 3, 4, 1);
        Shape2.setRotationPoint(-1.5F, 14F, 3F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
    }

    public void renderModel(float size, boolean emittingRedstone){
        // Shape1.render(size);
        if(emittingRedstone) {
            Shape2.render(size);
        } else {
            Shape1.render(size);
        }
    }

    private void setRotation(ModelRenderer model, float x, float y, float z){
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
